# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.operating-system }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        os: ${{ matrix.operating-system }}

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Installing `leetcode-cli`
      run: | 
        python -m pip install .

    - name: Running `leetcode-cli`
      run: | 
        leet config default_editor cat
        leet get random 
